# Generated by Django 5.2.4 on 2025-08-06 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('grade7', 'الصف الأول الإعدادي'), ('grade8', 'الصف الثاني الإعدادي'), ('grade9', 'الصف الثالث الإعدادي'), ('grade10', 'الصف الأول الثانوي'), ('grade11', 'الصف الثاني الثانوي'), ('grade12', 'الصف الثالث الثانوي')], max_length=10, unique=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('father_phone_number', models.CharField(max_length=20, verbose_name='رقم هاتف الأب')),
                ('age', models.PositiveIntegerField(verbose_name='العمر')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('august', 'أغسطس'), ('september', 'سبتمبر'), ('october', 'أكتوبر'), ('november', 'نوفمبر'), ('december', 'ديسمبر'), ('january', 'يناير'), ('february', 'فبراير'), ('march', 'مارس'), ('april', 'أبريل'), ('may', 'مايو'), ('june', 'يونيو')], max_length=10, verbose_name='الشهر')),
                ('year', models.IntegerField(default=2025, verbose_name='السنة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوع')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.student')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['year', 'month'],
                'unique_together': {('student', 'month', 'year')},
            },
        ),
    ]
