# Generated by Django 5.2.4 on 2025-08-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(choices=[('grade1', 'الصف الأول الإعدادي'), ('grade2', 'الصف الثاني الإعدادي'), ('grade3', 'الصف الثالث الإعدادي'), ('grade4', 'الصف الأول الثانوي'), ('grade5', 'الصف الثاني الثانوي'), ('grade6', 'الصف الثالث الثانوي')], max_length=100),
        ),
    ]
