# Generated by Django 5.2.4 on 2025-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_student_address_remove_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_exempt',
            field=models.BooleanField(default=False, verbose_name='معفي من الحسابات'),
        ),
    ]
