# Generated by Django 5.2.4 on 2025-08-08 11:17

from django.db import migrations


def set_default_exempt_status(apps, schema_editor):
    """Set all existing students as not exempt"""
    Student = apps.get_model('core', 'Student')
    Student.objects.filter(is_exempt__isnull=True).update(is_exempt=False)


def reverse_exempt_status(apps, schema_editor):
    """Reverse operation - not needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_is_exempt'),
    ]

    operations = [
        migrations.RunPython(set_default_exempt_status, reverse_exempt_status),
    ]
