# Generated by Django 5.2.4 on 2025-08-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_grade_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='name',
        ),
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('grade1', 'الصف الأول الإعدادي'), ('grade2', 'الصف الثاني الإعدادي'), ('grade3', 'الصف الثالث الإعدادي'), ('grade4', 'الصف الأول الثانوي'), ('grade5', 'الصف الثاني الثانوي'), ('grade6', 'الصف الثالث الثانوي')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
