# Generated by Django 5.2.4 on 2025-08-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_grade_name_grade_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='slug',
        ),
    ]
